[config]
reload_on_change = true
contrast = 0.0
scheme = "neutral" # Options: "content", "expressive", "fidelity", "fruit_salad", "monochrome", "neutral", "rainbow", "tonal_spot"

[templates.hypr]
input_path = "~/.config/matugen/templates/hypr.conf"
output_path = "~/.config/hypr/config/colors.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/custom.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.cava]
input_path = "~/.config/matugen/templates/cava"
output_path = "~/.config/cava/themes/custom"
post_hook = "pkill -SIGUSR1 cava"
